"""Explainable Alert Generation Engine for BDS-35.

Constructs comprehensive risk alerts with detailed factor provenance,
component breakdowns, and data status indicators.
"""
from __future__ import annotations
from datetime import datetime, timezone
from typing import Any


def create_alert(
    event_id: str,
    supplier_id: str | None,
    product_id: str | None,
    risk_result: dict[str, Any],
    reason: str | None = None,
    graph_risk: float = 0.0,
    combined_risk: float | None = None,
    combined_level: str | None = None,
    news_id: str = "",
    title: str = "",
    source: str = "",
    url: str = "",
    published_at: str = "",
    event_type: str = "Disruption",
    event_location: str = "Unknown",
    geographic_exposure: float = 0.20,
    distance_km: float | None = None,
    supplier_name: str | None = None,
    product_name: str | None = None,
    location_id: str | None = None,
    data_status: str = "SYNTHETIC_DEMO",
) -> dict[str, Any]:
    """Generate an explainable early-warning alert record."""
    det_score = float(risk_result.get("risk_score", 50.0))
    det_level = str(risk_result.get("risk_level", "MEDIUM"))

    if combined_risk is None:
        # Standard blending: 65% deterministic + 35% graph propagation
        combined_risk = round(0.65 * det_score + 0.35 * float(graph_risk), 2)

    if combined_level is None:
        if combined_risk >= 80.0:
            combined_level = "CRITICAL"
        elif combined_risk >= 60.0:
            combined_level = "HIGH"
        elif combined_risk >= 40.0:
            combined_level = "MEDIUM"
        else:
            combined_level = "LOW"

    alert_id = f"ALT-{event_id}" if not str(event_id).startswith("ALT-") else str(event_id)

    components = risk_result.get("components", {})

    return {
        "alert_id": alert_id,
        "event_id": event_id,
        "news_id": news_id,
        "title": title,
        "source": source,
        "url": url,
        "published_at": published_at,
        "event_type": event_type,
        "event_location": event_location,
        "location_id": location_id,
        "supplier_id": supplier_id,
        "supplier_name": supplier_name or (f"Supplier {supplier_id}" if supplier_id else "Unlinked Supplier"),
        "product_id": product_id,
        "product_name": product_name or (f"Product {product_id}" if product_id else "Unlinked Product"),
        "geographic_exposure": round(float(geographic_exposure), 3),
        "distance_km": round(float(distance_km), 2) if distance_km is not None else None,
        "deterministic_risk": det_score,
        "risk_score": det_score,  # Compatibility alias
        "risk_level": det_level,
        "graph_risk_score": round(float(graph_risk), 2),
        "combined_risk_score": combined_risk,
        "combined_risk_level": combined_level,
        "combined_risk": combined_risk,
        "combined_level": combined_level,
        "primary_driver": risk_result.get("primary_driver", "Event Severity"),
        "reason": reason or risk_result.get("explanation", "Early warning generated by BDS-35 risk engine."),
        "components": components,
        "data_status": data_status,
        "status": "ACTIVE",
        "created_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
