"""Configuration for the Deterministic Risk Engine (Phase 7).

Manages factor weights, category mappings, normalization scales, risk bands,
and academic taxonomy distinctions (HEURISTIC RISK vs MODEL OUTPUT vs GROUND TRUTH).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping


class RiskClassificationType(str, Enum):
    """Explicit taxonomy to distinguish risk score provenance and epistemology.

    - HEURISTIC_RISK: Rule-based, domain-weighted deterministic calculation.
                      Not a ground-truth label nor a machine-learned prediction.
    - MODEL_OUTPUT:   Predicted representation generated by GraphSAGE / GAT / ML models.
    - GROUND_TRUTH:   Empirically verified, post-disruption real-world operational outcome.
    """
    HEURISTIC_RISK = "HEURISTIC_RISK"
    MODEL_OUTPUT = "MODEL_OUTPUT"
    GROUND_TRUTH = "GROUND_TRUTH"


class RiskBand(str, Enum):
    """Categorical risk tiers based on normalized score [0.0, 1.0]."""
    LOW = "LOW"             # [0.00, 0.40)
    MEDIUM = "MEDIUM"       # [0.40, 0.60)
    HIGH = "HIGH"           # [0.60, 0.75)
    CRITICAL = "CRITICAL"   # [0.75, 1.00]


# Standardized categorical mapping dictionaries to [0.0, 1.0]

SEVERITY_MAPPING: dict[str, float] = {
    "1": 0.20, "2": 0.40, "3": 0.60, "4": 0.80, "5": 1.00,
    "1.0": 0.20, "2.0": 0.40, "3.0": 0.60, "4.0": 0.80, "5.0": 1.00,
    "low": 0.25, "medium": 0.50, "high": 0.75, "critical": 1.00,
    "minor": 0.25, "moderate": 0.50, "severe": 0.85, "catastrophic": 1.00,
    "unknown": 0.50,
}

CRITICALITY_MAPPING: dict[str, float] = {
    "low": 0.25, "medium": 0.50, "high": 0.85, "critical": 1.00,
    "tier-3": 0.35, "tier-2": 0.65, "tier-1": 1.00,
    "tier 3": 0.35, "tier 2": 0.65, "tier 1": 1.00,
    "non-critical": 0.25, "core": 0.85, "essential": 1.00,
    "unknown": 0.40,
}

DEPENDENCY_MAPPING: dict[str, float] = {
    "low": 0.25, "medium": 0.50, "high": 0.85, "critical": 1.00,
    "none": 0.00, "indirect": 0.35, "direct": 0.75, "sole": 1.00,
    "unknown": 0.50,
}

SINGLE_SOURCE_MAPPING: dict[str, float] = {
    "true": 1.00, "yes": 1.00, "1": 1.00, "single": 1.00, "sole": 1.00,
    "false": 0.00, "no": 0.00, "0": 0.00, "dual": 0.00, "multi": 0.00,
    "unknown": 0.30,
}


@dataclass(frozen=True)
class RiskWeightsConfig:
    """Configurable weights for the 6 candidate risk factors.

    Weights must be non-negative and sum to 1.0.
    """
    event_severity: float = 0.25
    geographic_exposure: float = 0.20
    supplier_criticality: float = 0.15
    product_criticality: float = 0.15
    dependency_strength: float = 0.15
    single_source_dependency: float = 0.10

    def __post_init__(self) -> None:
        total = (
            self.event_severity
            + self.geographic_exposure
            + self.supplier_criticality
            + self.product_criticality
            + self.dependency_strength
            + self.single_source_dependency
        )
        if not (0.999 <= total <= 1.001):
            raise ValueError(f"Risk factor weights must sum to 1.0 (current sum: {total:.4f})")

    def to_dict(self) -> dict[str, float]:
        """Convert weights to dictionary."""
        return {
            "event_severity": self.event_severity,
            "geographic_exposure": self.geographic_exposure,
            "supplier_criticality": self.supplier_criticality,
            "product_criticality": self.product_criticality,
            "dependency_strength": self.dependency_strength,
            "single_source_dependency": self.single_source_dependency,
        }


@dataclass
class DeterministicRiskConfig:
    """Master configuration for deterministic risk evaluation."""
    weights: RiskWeightsConfig = field(default_factory=RiskWeightsConfig)
    scale_to_100: bool = True  # Produce both [0,1] and [0,100] scale

    # Risk band thresholds on [0.0, 1.0] scale
    band_thresholds: tuple[tuple[float, RiskBand], ...] = (
        (0.75, RiskBand.CRITICAL),
        (0.60, RiskBand.HIGH),
        (0.40, RiskBand.MEDIUM),
        (0.00, RiskBand.LOW),
    )

    def determine_band(self, normalized_score: float) -> RiskBand:
        """Assign risk band based on normalized score [0.0, 1.0]."""
        for threshold, band in self.band_thresholds:
            if normalized_score >= threshold:
                return band
        return RiskBand.LOW


DEFAULT_DETERMINISTIC_CONFIG = DeterministicRiskConfig()
